public with sharing class Constants {
    public static final String TOUR_CG_TOUR_COMPLETED             = 'Tour completed';
    public static final String TOUR_CG_CLIENT_COMMITMENT          = 'Client commitment';
    public static final String TOUR_CG_PROPOSAL_GENERATED         = 'Proposal Generated';
    public static final String TOUR_STATUS_ACTIVE                 = 'Active';
    public static final String TOUR_STATUS_COMPLETED              = 'Completed';
    public static final String TOUR_STATUS_DECLINED               = 'Declined';
    public static final String TOUR_STATUS_INCOMPLETED            = 'Incompleted';
    public static final String OPPORTUNITY_STAGE_NEW              = 'New';
    public static final String OPPORTUNITY_STAGE_TOUR_COMPLETED   = 'Tour completed';
    public static final String OPPORTUNITY_STAGE_READY_COMMITMENT = 'Ready for Commitment';
    public static final String OPPORTUNITY_STAGE_CLOSED_WON       = 'Closed Won';
    public static final String ACCOUNT_STATUS_NEW                 = 'New';
    public static final String ACCOUNT_STATUS_IN_PROGRESS         = 'In progress';
    public static final String ACCOUNT_STATUS_CURRENT_CUSTOMER    = 'Current customer';
}
